# Generated by Django 4.2.4 on 2023-11-15 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_group', models.BooleanField(default=False, verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo',
                 stdimage.models.StdImageField(default='profile_photos/defaultProfile.png', force_min_size=False,
                                               upload_to='profile_photos',
                                               variations={'thumb': {'crop': True, 'height': 600, 'width': 600}},
                                               verbose_name='Foto de Perfil')),
                ('is_online', models.BooleanField(default=False, verbose_name='online')),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation',
                 models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages',
                                   to='chats.conversation')),
                ('sender', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='sent_messages', to='chats.profile')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='GroupNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo',
                 stdimage.models.StdImageField(default='profile_photos/default_group_profile.png', force_min_size=False,
                                               upload_to='profile_photos',
                                               variations={'thumb': {'crop': True, 'height': 600, 'width': 600}},
                                               verbose_name='Foto de Perfil')),
                ('chat',
                 models.OneToOneField(limit_choices_to={'is_group': True}, on_delete=django.db.models.deletion.CASCADE,
                                      to='chats.conversation')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to='chats.profile'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends',
                                             to='chats.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts',
                                           to='chats.profile')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='read_status', to='chats.message')),
                ('recipientProfile',
                 models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='chats.profile')),
            ],
            options={
                'unique_together': {('recipientProfile', 'message')},
            },
        ),
    ]
