# Generated by Django 4.2.4 on 2023-11-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='grupo'),
        ),
    ]
