# Generated by Django 4.2.4 on 2023-10-21 07:26

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_profile_alter_conversation_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=stdimage.models.StdImageField(default='profile_photos/defaultProfile.png', force_min_size=False, upload_to='profile_photos', variations={'thumb': {'crop': True, 'height': 600, 'width': 600}}),
        ),
    ]
