# Generated by Django 4.2.4 on 2023-10-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_profile_avatar_profile_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
