# Generated by Django 4.2.4 on 2023-10-22 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='foto',
            new_name='photo',
        ),
    ]
