# Generated by Django 4.2.4 on 2023-10-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_rename_foto_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
