# Generated by Django 4.2.4 on 2023-10-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_alter_conversation_options_message_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
    ]
