# Generated by Django 4.2.4 on 2023-11-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_alter_message_content_alter_message_conversation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
