# Generated by Django 4.2.4 on 2023-11-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
